language: node_js
node_js: '7'
before_script: npm install
script: npm run build
branches:
  only:
    - source
cache:
  directories:
  - node_modules
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    target_branch: master
    on:
      branch: source
